# Generated by Django 4.2.16 on 2024-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesbase', '0002_recipe_description_recipe_image_recipe_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptionCategory',
            field=models.TextField(null=True),
        ),
    ]
